### ISSUE TITLE
Align resource manager with SAL API

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/resource-manager#50]
On PROD env, Resource manager is using an old terminology for CPU and RAM when registering edge devices on SAL:

https://github.com/eu-nebulous/resource-manager/blob/b3eec9e937ab61744dce94c1c0c27657c202f992/resource-discovery/src/main/java/eu/nebulous/resource/discovery/broker_communication/SALCommunicator.java#L107

memory should be now referred as  ram
numberOfCores should be now referred as  cores

Refer to https://openproject.nebulouscloud.eu/projects/nebulous-2nd-release-1/work_packages/514/activity for further details

**Comment by atsag** [comment]
Should be fixed by the latest PR (https://github.com/eu-nebulous/resource-manager/pull/52)

**Comment by robert-sanfeliu** [comment]
After merging to r1, inform 7bulls so they can push it to production

**Comment by robert-sanfeliu** [comment]
@atsag , please provide value for `fpga` too
